plugins {
    id 'eclipse'
    id 'idea'
    id 'net.minecraftforge.gradle' version '6.0.54'
}

version = "1.3.0-MC26.1-forge"
group = "com.eliasnvx.forge"

base {
    archivesName = 'krylix'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

minecraft {
    mappings channel: 'official', version: '26.1'
    reobf = false
    copyIdeResources = true

    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'debug'
        }
        client {
            property 'forge.enabledGameTestNamespaces', 'krylix'
        }
        server {
            property 'forge.enabledGameTestNamespaces', 'krylix'
            args '--nogui'
        }
    }
}

sourceSets {
    main {
        java {
            srcDir project(':common').sourceSets.main.java.srcDirs
        }
        resources {
            srcDir project(':common').sourceSets.main.resources.srcDirs
        }
    }
}

dependencies {
    minecraft 'net.minecraftforge:forge:26.1-26.1.0'
    implementation 'me.shedaniel.cloth:cloth-config-forge:26.1.154'
    compileOnly project(':common')
}

tasks.named('processResources', ProcessResources).configure {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.named('jar', Jar).configure {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    archiveBaseName.set('krylix')
}
